#!/bin/bash

# 🚀 CCXT Integration System - Installation Script
# Install required dependencies for the exchange integration system

echo "🌐 Installing CCXT Exchange Integration System..."
echo ""

# Install CCXT library
echo "📦 Installing CCXT library..."
npm install ccxt

echo ""
echo "✅ Installation complete!"
echo ""
echo "📚 System Structure:"
echo "  ✅ Core Files (6)"
echo "     - types.ts"
echo "     - config.ts"
echo "     - cache.ts"
echo "     - rate-limiter.ts"
echo "     - ccxt-manager.ts"
echo "     - aggregator.ts"
echo ""
echo "  ✅ Exchange Integrations (10)"
echo "     - Binance (Spot + USDⓈ-M Futures)"
echo "     - Bybit (Spot + Linear Futures)"
echo "     - OKX (Spot + Swap)"
echo "     - Bitget (Spot + Futures)"
echo "     - KuCoin (Spot + Futures)"
echo ""
echo "  ✅ API Routes (6)"
echo "     - /api/exchanges/ticker"
echo "     - /api/exchanges/orderbook"
echo "     - /api/exchanges/ohlcv"
echo "     - /api/exchanges/trades"
echo "     - /api/exchanges/markets"
echo "     - /api/exchanges/aggregated"
echo ""
echo "  ✅ React Integration (2)"
echo "     - hooks/useExchangeData.ts"
echo "     - stores/exchangeStore.ts"
echo ""
echo "  ✅ Example Components (2)"
echo "     - components/TradingDashboard.tsx"
echo "     - components/MultiExchangeComparison.tsx"
echo ""
echo "📖 Read CCXT_INTEGRATION_README.md for usage examples"
echo ""
echo "🎯 Quick Start:"
echo "  1. Import hooks:"
echo "     import { useTicker, useOrderBook } from '@/hooks/useExchangeData';"
echo ""
echo "  2. Use in component:"
echo "     const { data, loading, error } = useTicker({ exchange: 'binance', symbol: 'BTC/USDT' });"
echo ""
echo "  3. Access API routes:"
echo "     fetch('/api/exchanges/ticker?exchange=binance&symbol=BTC/USDT')"
echo ""
echo "🔥 Happy Trading!"
