/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * CANVAS EXPORT MENU
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * قائمة تصدير شاملة مع دعم متعدد للصيغ
 * مثل نظام Claude Canvas
 * 
 * @version 1.0.0
 */

'use client';

import { useState } from 'react';
import { useCanvasStore } from '@/store/canvasStore';
import { Download, FileText, FileCode, Image, Loader2, Check } from 'lucide-react';
import { toPng } from 'html-to-image';

type ExportFormat = 'markdown' | 'pdf' | 'png' | 'code';

interface ExportMenuProps
{
    onClose?: () => void;
}

export function ExportMenu ( { onClose }: ExportMenuProps )
{
    const { versions, currentVersionIndex, title, language, type } = useCanvasStore();
    const currentVersion = versions[ currentVersionIndex ];
    const [ exporting, setExporting ] = useState<ExportFormat | null>( null );
    const [ exported, setExported ] = useState<ExportFormat | null>( null );

    // Helper: Download file
    const downloadFile = ( content: string, filename: string, mimeType: string ) =>
    {
        const blob = new Blob( [ content ], { type: mimeType } );
        const url = URL.createObjectURL( blob );
        const link = document.createElement( 'a' );
        link.href = url;
        link.download = filename;
        document.body.appendChild( link );
        link.click();
        document.body.removeChild( link );
        URL.revokeObjectURL( url );
    };

    // Helper: Get file extension
    const getFileExtension = ( lang: string ): string =>
    {
        const extensions: Record<string, string> = {
            typescript: '.tsx',
            javascript: '.js',
            html: '.html',
            css: '.css',
            python: '.py',
            java: '.java',
            cpp: '.cpp',
            csharp: '.cs',
            go: '.go',
            rust: '.rs',
            php: '.php',
            ruby: '.rb',
            swift: '.swift',
            kotlin: '.kt',
            markdown: '.md',
            json: '.json',
            yaml: '.yml',
            xml: '.xml',
        };
        return extensions[ lang ] || '.txt';
    };

    // Export as Markdown
    const exportMarkdown = async () =>
    {
        setExporting( 'markdown' );
        try
        {
            const content = currentVersion?.content || '';
            const markdown = type === 'CODE'
                ? `# ${ title }\n\n\`\`\`${ language }\n${ content }\n\`\`\``
                : content;

            downloadFile( markdown, `${ title }.md`, 'text/markdown' );
            setExported( 'markdown' );
            setTimeout( () => setExported( null ), 2000 );
        } catch ( error )
        {
            console.error( 'Export markdown error:', error );
        } finally
        {
            setExporting( null );
        }
    };

    // Export as PDF
    const exportPDF = async () =>
    {
        setExporting( 'pdf' );
        try
        {
            // Import html2pdf dynamically to avoid server-side issues
            const html2pdf = ( await import( 'html2pdf.js' ) ).default;

            const content = currentVersion?.content || '';

            // Create styled HTML
            const html = `
        <div style="font-family: 'Monaco', 'Menlo', monospace; padding: 40px; line-height: 1.6;">
          <h1 style="color: #333; border-bottom: 2px solid #6366f1; padding-bottom: 10px;">${ title }</h1>
          <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin-top: 20px;">
            <pre style="white-space: pre-wrap; word-wrap: break-word; margin: 0; font-size: 12px;">${ content }</pre>
          </div>
          <div style="margin-top: 30px; color: #666; font-size: 10px; text-align: center;">
            Generated by Nexus Canvas • ${ new Date().toLocaleString() }
          </div>
        </div>
      `;

            const opt = {
                margin: 10,
                filename: `${ title }.pdf`,
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
            };

            await html2pdf().set( opt ).from( html ).save();
            setExported( 'pdf' );
            setTimeout( () => setExported( null ), 2000 );
        } catch ( error )
        {
            console.error( 'Export PDF error:', error );
        } finally
        {
            setExporting( null );
        }
    };

    // Export as PNG
    const exportPNG = async () =>
    {
        setExporting( 'png' );
        try
        {
            const canvasElement = document.querySelector( '.monaco-editor' ) ||
                document.querySelector( '.tiptap' ) ||
                document.querySelector( '.canvas-content' );

            if ( !canvasElement )
            {
                throw new Error( 'Canvas element not found' );
            }

            const dataUrl = await toPng( canvasElement as HTMLElement, {
                quality: 1,
                pixelRatio: 2,
                backgroundColor: '#1e1e1e',
            } );

            const link = document.createElement( 'a' );
            link.download = `${ title }.png`;
            link.href = dataUrl;
            link.click();

            setExported( 'png' );
            setTimeout( () => setExported( null ), 2000 );
        } catch ( error )
        {
            console.error( 'Export PNG error:', error );
        } finally
        {
            setExporting( null );
        }
    };

    // Export as Code File
    const exportCodeFile = async () =>
    {
        setExporting( 'code' );
        try
        {
            const content = currentVersion?.content || '';
            const extension = getFileExtension( language );
            const filename = title.includes( '.' ) ? title : `${ title }${ extension }`;
            const mimeType = type === 'CODE' ? 'text/plain' : 'text/markdown';

            downloadFile( content, filename, mimeType );
            setExported( 'code' );
            setTimeout( () => setExported( null ), 2000 );
        } catch ( error )
        {
            console.error( 'Export code error:', error );
        } finally
        {
            setExporting( null );
        }
    };

    const exportOptions = [
        {
            id: 'markdown' as ExportFormat,
            label: 'Markdown',
            description: 'تصدير كملف Markdown',
            icon: FileText,
            onClick: exportMarkdown,
        },
        {
            id: 'pdf' as ExportFormat,
            label: 'PDF Document',
            description: 'تصدير كملف PDF',
            icon: FileText,
            onClick: exportPDF,
        },
        {
            id: 'png' as ExportFormat,
            label: 'PNG Image',
            description: 'حفظ كصورة',
            icon: Image,
            onClick: exportPNG,
        },
        {
            id: 'code' as ExportFormat,
            label: `Code File (${ getFileExtension( language ) })`,
            description: 'تحميل كملف برمجي',
            icon: FileCode,
            onClick: exportCodeFile,
        },
    ];

    return (
        <div className="absolute right-0 top-full mt-2 w-72 rounded-lg border border-border bg-background shadow-xl z-50 animate-in fade-in slide-in-from-top-2 duration-200">
            <div className="p-3 border-b border-border">
                <h3 className="text-sm font-semibold flex items-center gap-2">
                    <Download className="w-4 h-4" />
                    تصدير Canvas
                </h3>
            </div>

            <div className="p-2 space-y-1">
                { exportOptions.map( ( option ) =>
                {
                    const Icon = option.icon;
                    const isExporting = exporting === option.id;
                    const isExported = exported === option.id;

                    return (
                        <button
                            key={ option.id }
                            onClick={ option.onClick }
                            disabled={ !!exporting }
                            className="w-full flex items-start gap-3 p-3 rounded-lg hover:bg-muted transition-colors disabled:opacity-50 disabled:cursor-not-allowed text-left group"
                        >
                            <div className="shrink-0 mt-0.5">
                                { isExporting ? (
                                    <Loader2 className="w-4 h-4 animate-spin text-primary" />
                                ) : isExported ? (
                                    <Check className="w-4 h-4 text-green-500" />
                                ) : (
                                    <Icon className="w-4 h-4 text-muted-foreground group-hover:text-foreground transition-colors" />
                                ) }
                            </div>
                            <div className="flex-1 min-w-0">
                                <div className="text-sm font-medium">
                                    { isExported ? 'تم التصدير بنجاح!' : option.label }
                                </div>
                                <div className="text-xs text-muted-foreground mt-0.5">
                                    { option.description }
                                </div>
                            </div>
                        </button>
                    );
                } ) }
            </div>

            { onClose && (
                <div className="p-2 border-t border-border">
                    <button
                        onClick={ onClose }
                        className="w-full text-xs text-muted-foreground hover:text-foreground py-2 transition-colors"
                    >
                        إغلاق
                    </button>
                </div>
            ) }
        </div>
    );
}
